In [1]:
import sys

if 'google.colab' in sys.modules:

    print("Running in Google Colab")

    print(f"Python version: {sys.version}")

else:

    print("Not running in Google Colab")

Running in Google Colab
Python version: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]

# **Importar datos**

In [2]:
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
import pandas as pd
# La ruta estándar a la raíz de tu unidad es esta:

path = '/content/drive/MyDrive/Botacampo/kiva_loans.csv'

 

# Cargar el archivo

df = pd.read_csv(path)

 

# Ver las primeras filas

df.head()

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Botacampo/kiva_loans.csv'

In [4]:
import pandas as pd

df = pd.read_csv('/content/kiva_loans_42304_rows.csv')

df.head()

FileNotFoundError: [Errno 2] No such file or directory: '/content/kiva_loans_42304_rows.csv'

In [ ]:
df.shape
df.info()
df.describe(include='all')
df.count()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 671205 entries, 0 to 671204
Data columns (total 20 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   id                  671205 non-null  int64
 1   funded_amount       671205 non-null  float64
 2   loan_amount         671205 non-null  float64
 3   activity            671205 non-null  object
 4   sector              671205 non-null  object
 5   use                 666973 non-null  object
 6   country_code        671197 non-null  object
 7   country             671205 non-null  object
 8   region              614405 non-null  object
 9   currency            671205 non-null  object
 10  partner_id          657698 non-null  float64
 11  posted_time         671205 non-null  object
 12  disbursed_time      668809 non-null  object
 13  funded_time         622874 non-null  datetime64[ns, UTC]
 14  term_in_months      671205 non-null  float64
 15  lender_count        671205 non-null  int64
 16  tags                499789 non-null  object
 17  borrower_genders    666984 non-null  object
 18  repayment_interval  671205 non-null  object
 19  date                671205 non-null  datetime64[ns]
dtypes: datetime64[ns, UTC](1), datetime64[ns](1), float64(4), int64(2), object(12)
memory usage: 102.4+ MB

id                    671205
funded_amount         671205
loan_amount           671205
activity              671205
sector                671205
use                   666973
country_code          671197
country               671205
region                614405
currency              671205
partner_id            657698
posted_time           671205
disbursed_time        668809
funded_time           622874
term_in_months        671205
lender_count          671205
tags                  499789
borrower_genders      666984
repayment_interval    671205
date                  671205
dtype: int64

In [ ]:
#Duplicados
df.duplicated().sum()
#Valores Nulos
df.isnull().sum().sort_values(ascending=False)
df['loan_amount'].describe()

count    671205.000000
mean        842.397107
std        1198.660073
min          25.000000
25%         275.000000
50%         500.000000
75%        1000.000000
max      100000.000000
Name: loan_amount, dtype: float64

# **Limpieza de datos**

In [ ]:
#Fechas
df['date'] = pd.to_datetime(df['date'], errors='coerce')
df['funded_time'] = pd.to_datetime(df['funded_time'], errors='coerce')
#Eliminar duplicados
df = df.drop_duplicates()
#Valores en blanco
# Eliminar filas sin información
df = df.dropna(subset=['loan_amount', 'country'])
# Rellenar valores en blanco
df['sector'] = df['sector'].fillna('Sin datos')